version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bionicpro
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - bionicpro
    depends_on:
      - keycloak_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bionicpro
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
  crm_db:
    image: postgres:14
    volumes:
      - ./crm-db:/docker-entrypoint-initdb.d
    ports:
      - "9951:5432"
    environment:
      POSTGRES_DB: bionicpro
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    networks:
      - bionicpro
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - airflow
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  telemetry_db:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./telemetry-db:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    environment:
      CLICKHOUSE_USER: airflow
      CLICKHOUSE_PASSWORD: airflow
      CLICKHOUSE_DB: bionicpro
    networks:
      - bionicpro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    restart: always

networks:
  bionicpro:
